<?php

/**
 * BaseAlbum
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $image
 * @property integer $year
 * @property boolean $is_activated
 * @property boolean $is_va
 * 
 * @method string  getTitle()        Returns the current record's "title" value
 * @method string  getImage()        Returns the current record's "image" value
 * @method integer getYear()         Returns the current record's "year" value
 * @method boolean getIsActivated()  Returns the current record's "is_activated" value
 * @method boolean getIsVa()         Returns the current record's "is_va" value
 * @method Album   setTitle()        Sets the current record's "title" value
 * @method Album   setImage()        Sets the current record's "image" value
 * @method Album   setYear()         Sets the current record's "year" value
 * @method Album   setIsActivated()  Sets the current record's "is_activated" value
 * @method Album   setIsVa()         Sets the current record's "is_va" value
 * 
 * @package    chiptunedb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAlbum extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('album');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('year', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('is_activated', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('is_va', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}