<?php

/**
 * BaseArtist
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $alias
 * @property string $url
 * @property string $image
 * @property boolean $is_activated
 * @property integer $country_id
 * @property Country $Country
 * @property Doctrine_Collection $Track
 * 
 * @method integer             getId()           Returns the current record's "id" value
 * @method string              getName()         Returns the current record's "name" value
 * @method string              getAlias()        Returns the current record's "alias" value
 * @method string              getUrl()          Returns the current record's "url" value
 * @method string              getImage()        Returns the current record's "image" value
 * @method boolean             getIsActivated()  Returns the current record's "is_activated" value
 * @method integer             getCountryId()    Returns the current record's "country_id" value
 * @method Country             getCountry()      Returns the current record's "Country" value
 * @method Doctrine_Collection getTrack()        Returns the current record's "Track" collection
 * @method Artist              setId()           Sets the current record's "id" value
 * @method Artist              setName()         Sets the current record's "name" value
 * @method Artist              setAlias()        Sets the current record's "alias" value
 * @method Artist              setUrl()          Sets the current record's "url" value
 * @method Artist              setImage()        Sets the current record's "image" value
 * @method Artist              setIsActivated()  Sets the current record's "is_activated" value
 * @method Artist              setCountryId()    Sets the current record's "country_id" value
 * @method Artist              setCountry()      Sets the current record's "Country" value
 * @method Artist              setTrack()        Sets the current record's "Track" collection
 * 
 * @package    chiptunedb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseArtist extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('artist');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('alias', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('is_activated', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('country_id', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => true,
             'unique' => true,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Country', array(
             'local' => 'country_id',
             'foreign' => 'id'));

        $this->hasMany('Track', array(
             'local' => 'id',
             'foreign' => 'artist_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}