<?php

/**
 * BaseCountry
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $iso
 * @property string $name
 * @property string $printable_name
 * @property string $iso3
 * @property integer $numcode
 * @property Doctrine_Collection $Artist
 * 
 * @method integer             getId()             Returns the current record's "id" value
 * @method string              getIso()            Returns the current record's "iso" value
 * @method string              getName()           Returns the current record's "name" value
 * @method string              getPrintableName()  Returns the current record's "printable_name" value
 * @method string              getIso3()           Returns the current record's "iso3" value
 * @method integer             getNumcode()        Returns the current record's "numcode" value
 * @method Doctrine_Collection getArtist()         Returns the current record's "Artist" collection
 * @method Country             setId()             Sets the current record's "id" value
 * @method Country             setIso()            Sets the current record's "iso" value
 * @method Country             setName()           Sets the current record's "name" value
 * @method Country             setPrintableName()  Sets the current record's "printable_name" value
 * @method Country             setIso3()           Sets the current record's "iso3" value
 * @method Country             setNumcode()        Sets the current record's "numcode" value
 * @method Country             setArtist()         Sets the current record's "Artist" collection
 * 
 * @package    chiptunedb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCountry extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('country');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'unique' => true,
             ));
        $this->hasColumn('iso', 'string', 2, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 2,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('printable_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('iso3', 'string', 3, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 3,
             ));
        $this->hasColumn('numcode', 'integer', 3, array(
             'type' => 'integer',
             'notnull' => true,
             'unique' => true,
             'length' => 3,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Artist', array(
             'local' => 'id',
             'foreign' => 'country_id'));
    }
}