label:
  class: sfDoctrineRouteCollection
  options:
    model:                Label
    module:               label
    prefix_path:          /label
    column:               id
    with_wildcard_routes: true

album:
  class: sfDoctrineRouteCollection
  options:
    model:                Album
    module:               album
    prefix_path:          /album
    column:               id
    with_wildcard_routes: true

country:
  class: sfDoctrineRouteCollection
  options:
    model:                Country
    module:               country
    prefix_path:          /country
    column:               id
    with_wildcard_routes: true

artist:
  class: sfDoctrineRouteCollection
  options:
    model:                Artist
    module:               artist
    prefix_path:          /artist
    column:               id
    with_wildcard_routes: true

track:
  class: sfDoctrineRouteCollection
  options:
    model:                Track
    module:               track
    prefix_path:          /track
    column:               id
    with_wildcard_routes: true

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: default, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
