<?php

/**
 * LabelTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LabelTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LabelTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Label');
    }
}