---
detect_relations:     true

Artist:
  actAs: { Timestampable: ~ }
  columns:
    id: { type: integer, autoincrement: true, primary: true, notnull: true }
    name: { type: string(255), notnull: true, unique: true }
    alias: { type: string(255) }
    url: { type: string(255) }
    image: { type: string(255) }
    is_activated: { type: boolean, notnull: true, default: 0 }
    country_id: { type: integer, notnull: true }

Country:
  columns:
    id: { type: integer, autoincrement: true, primary: true, notnull: true }
    iso: { type: string(2), notnull: true, unique: true }
    name: { type: string(255), notnull: true, unique: true }
    printable_name: { type: string(255), notnull: true, unique: true }
    iso3: { type: string(3), notnull: true, unique: true }
    numcode: { type: integer(3), notnull: true, unique: true }

Track:
  actAs: { Timestampable: ~ }
  columns:
    id: { type: integer, autoincrement: true, primary: true, notnull: true }
    title: { type: string(255), notnull: true, unique: true }
    number: { type: string(255), notnull: true }
    artist_id: { type: integer, notnull: true }
    album_id: { type: integer, notnull: true }

Album:
  actAs: { Timestampable: ~ }
  columns:
    id: { type: integer, autoincrement: true, primary: true, notnull: true }
    title: { type: string(255), notnull: true, unique: true }
    image: { type: string(255) }
    year: { type: integer(4) }
    dl_url: { type: string(255) }
    is_activated: { type: boolean, notnull: true, default: 0 }
    is_va: { type: boolean, notnull: true, default: 0 }
    label_id: { type: integer, notnull: true }

Label:
  actAs: { Timestampable: ~ }
  columns:
    id: { type: integer, autoincrement: true, primary: true, notnull: true }
    name: { type: string(255), notnull: true, unique: true }
    logo: { type: string(255) }
    url: { type: string(255) }