---
detect_relations:     true

Artist:
  actAs: { Timestampable: ~ }
  columns:
    id: { type: integer, autoincrement: true, primary: true, notnull: true }
    name: { type: string(255), notnull: true, unique: true }
    country: { type: string(255), notnull: true }
    url: { type: string(255)  }
    is_activated: { type: boolean, notnull: true, default: 0 }

Track:
  actAs: { Timestampable: ~ }
  columns:
    title: { type: string(255), notnull: true, unique: true }
    number: { type: string(255), notnull: true }
    artist_id: { type: integer, notnull: true }

Album:
  actAs: { Timestampable: ~ }
  columns:
    title: { type: string(255), notnull: true, unique: true }
    image: { type: string(255)  }
    year: { type: integer(4)  }
    is_activated: { type: boolean, notnull: true, default: 0 }
    is_va: { type: boolean, notnull: true, default: 0 }